apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-lsfrkvve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-lsfrkvve 
  name: go-lsfrkvve
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-lsfrkvve
    weight: 100 
